name: Build and Test ASP.NET Core
on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  build-and-test:
    runs-on: windows-2022

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Display GitHub Actions Environment
        run: dotnet --info
      - name: SETUP .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          # You can test your matrix by printing the current dotnet version
      - name: Display dotnet version
        run: dotnet --version

      - name: Restore Nuget Packages
        run: dotnet restore
      - name: Build Africuisine Solution
        run: dotnet build --configuration Release
      - name: Run NUnit Tests
        run: dotnet test --configuration Release Africuisine.Tests/Africuisine.Tests.csproj --no-restore
